# Generated by Django 2.2.5 on 2020-08-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Event', 'Event'), ('Training', 'Training'), ('Blog Post', 'Blog Post'), ('Tutorial', 'Tutorial')], default='Event', max_length=20),
        ),
    ]
