# Generated by Django 2.0.13 on 2020-03-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons'),
        ),
    ]
