# Generated by Django 2.2.5 on 2020-08-26 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200827_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='img1',
            new_name='landing_image',
        ),
    ]
