# Generated by Django 2.0.13 on 2020-03-17 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200316_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='gallery_image')),
                ('blog', models.ForeignKey(default='default.jpg', on_delete=django.db.models.deletion.CASCADE, to='myapp.Blog')),
            ],
        ),
    ]
