# Generated by Django 2.2.5 on 2020-08-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200827_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='img6',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='vid',
            field=models.FileField(blank=True, null=True, upload_to='blog_video/'),
        ),
    ]
