# Generated by Django 2.0.13 on 2020-03-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='youtube',
            field=models.URLField(null=True),
        ),
    ]
