# Generated by Django 2.2.5 on 2020-06-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200601_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='text',
            field=models.CharField(max_length=150),
        ),
    ]
